### ISSUE TITLE
PvP laeder signs are lost after server restart

### ISSUE THREAD

**Issue by Malachiel87** [BattlePlugins/BattleTracker#16]
PvP leaderboard signs are working fine, until at server restart, signs file will be reseted, no errors on console.

**Comment by Redned235** [comment]
Can’t say I’ve ran into this problem before. I have done some work with BattleTracker, but I’m not sure if that would “fix” this problem. I’ll keep this issue open for now and see if I can try and replicate the problem.

**Comment by Redned235** [comment]
Resolved in rewrite. Closing.
