### ISSUE TITLE
Errors with HideAndSeek

### ISSUE THREAD

**Issue by SeruhioX** [BattlePlugins/BattleTracker#17]
There is a bug with this plugin is that it records the data of hideandseek

I'm using 1.8.8 Spigot

`18.04 23:13:43 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
18.04 23:13:43 [Server] INFO at sun.reflect.GeneratedMethodAccessor318.invoke(Unknown Source) ~[?:?]
18.04 23:13:43 [Server] INFO at mc.alk.tracker.listeners.BTEntityListener.onPlayerDeath(BTEntityListener.java:66) ~[?:?]
18.04 23:13:43 [Server] INFO at mc.alk.tracker.listeners.BTEntityListener.ede(BTEntityListener.java:180) ~[?:?]
18.04 23:13:43 [Server] INFO at mc.alk.tracker.listeners.BTEntityListener.getPvPDeathMessage(BTEntityListener.java:287) ~[?:?]
18.04 23:13:43 [Server] INFO at mc.alk.tracker.controllers.MessageController.getPvPMessage(MessageController.java:141) ~[?:?]
18.04 23:13:43 [Server] INFO Caused by: java.lang.NullPointerException
18.04 23:13:43 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
18.04 23:13:43 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO at net.minecraft.server.v1_8_R3.EntityProjectile.t_(EntityProjectile.java:154) [spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO at net.minecraft.server.v1_8_R3.EntityPotion.a(EntityPotion.java:118) [spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO at net.minecraft.server.v1_8_R3.MobEffectList.applyInstantEffect(MobEffectList.java:139) [spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:811) [spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:417) [spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:395) [spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigotbajo.jar:git-Spigot-6c9b0a1-de5c261]
18.04 23:13:43 [Server] INFO org.bukkit.event.EventException
18.04 23:13:43 [Server] ERROR Could not pass event PlayerDeathEvent to BattleTracker v2.5.9.2`

**Comment by Europia79** [comment]
That copy & paste from the console window is painful to look at.
Please copy & paste from the log file as it's formatted & easier to read.

**Comment by Zach443** [comment]
@Europia79 while I agree, this was 2.5 years ago. I doubt this person still has the console logs or still uses this plugin combo. 

Not to mention, Spigot, BattleTracker, and probably the Hide and Seek plugin have all been updated many times since this report. The code has changed and tracking down this issue without a current stack trace is going to prove annoying and most likely useless. 

@SeDark If I happen to be wrong and you are actually still using these plugins feel free to chime in
