### ISSUE TITLE
1.9 

### ISSUE THREAD

**Issue by tara81** [BattlePlugins/BattleTracker#19]
5:14:57 PM
 CONSOLE:
ERROR]: null
5:14:57 PM
 CONSOLE:
exception executing command 'pvp' in plugin BattleTracker v2.5.9.3
5:14:58 PM
 CONSOLE:
java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;

**Comment by clovisd** [comment]
Okay?

The plugin is abandoned and no longer works (and hasn't for quite a while).

**Comment by Zach443** [comment]
Hey tara! As Clovis said, we haven't been working on the plugins for a while now. Maybe jump on IRC and we can talk.

**Comment by Zach443** [comment]
Vague, and old. Nothing really productive can come out of this, so closing.

**Comment by Europia79** [comment]
We need to make sure that BattleTracker isn't invoking Bukkit.getOnlinePlayers(), but instead using either the BukkitInterface Library OR BattleBukkitLib that also has it.

https://github.com/BattlePlugins/BattleTracker/blob/master/pom.xml#L46-L47

Which I see in the `pom.xml` that it's using an old version of BattleBukkitLib.
It should update to `v2.6.0`

**Comment by Europia79** [comment]
Of course, to clarifly, I'm talking about what will most likely be TWO different versions of `BattleTracker`:

One branch & build for 1.2.5 to 1.12

And with all the breaking changes in 1.13, we will most likely drop support for older versions of Minecraft, and therefore have BattleArena & BattleTracker support 1.13+

**Comment by Europia79** [comment]
So BattleTracker for 1.13+, it should be fine to invoke Bukkit.getOnlinePlayers() again.
