### ISSUE TITLE
UUID Support for 1.8 Name Changes

### ISSUE THREAD

**Issue by clovisd** [BattlePlugins/BattleTracker#2]
We need to add UUID support for BT 1.8, ideally, in the new few days-week. 

Mojang plan on allowing username changes on Feb 4th 2015.

See here: https://mojang.com/2015/01/announcing-minecraft-name-changes/

**Comment by Zach443** [comment]
Thanks for that catch! I need to come up with a new database structure, change the code to use UUID's, then write some code to convert the old tables to the new ones. Whew, easier said than done! :stuck_out_tongue_closed_eyes:

**Comment by lDucks** [comment]
I'm closing this, BattleArena works with UUIDs.

**Comment by Zach443** [comment]
While BattleArena does support UUIDs, BattleTracker does not. All of the database records (win/loss record, kill count, rating, etc) are limited to username only currently. An update like this is not as simple as swapping a few methods and telling people to update the plugin. Both UUIDs and usernames still need to be tracked, and normalization of databases and tables for existing users would be a very large task. I have discussed this update with alkarin, and we have come to the conclusion that this is not a necessary, or reasonable update at this time. For now, if you change your name, you must also lose your stats. 

If sometime in the future we see it necessary to add UUID support, this issue will be reopened.

**Comment by Europia79** [comment]
> For now, if you change your name, you must also lose your stats.

I agree. This is just the way it has to be for now.
