### ISSUE TITLE
SQL Connector config falsly creates username: eventhough config looks for user

### ISSUE THREAD

**Issue by Jodsderechte** [BattlePlugins/BattleTracker#26]
At https://github.com/BattlePlugins/BattleTracker/blob/96895c9fceed68c4229464c402306d624679ffff/src/main/resources/config.yml#L24 the config get's initialized at username but https://github.com/BattlePlugins/BattleTracker/blob/96895c9fceed68c4229464c402306d624679ffff/src/main/java/org/battleplugins/tracker/BattleTrackerConfig.java#L67 searches for user

**Comment by Zach443** [comment]
Nice find. Fixed 👍
