### ISSUE TITLE
People cant spectate games

### ISSUE THREAD

**Issue by deano3663** [BattlePlugins/BattleTracker#5]
Hey all im probably just being dumb but i cant seem to let people spectate games , ive set up spectator rooms and stuff but any time someone trys to do /arena watch (arenaname) it says that the arena does not have visitors enabled.

Please let me know if there's a command or whatever

**Comment by Zach443** [comment]
Hey deano, sorry we missed you in IRC earlier. Anyways, as for spectating; that feature is currently not working for some reason. We are investigating the problem and hoping to have it fixed in out upcoming update to BattleArena (v4.0). Sorry for the inconvenience, but stay tuned for more info!

**Comment by deano3663** [comment]
ah alright thanks for letting me know :)
