### ISSUE TITLE
BT Scoreboard Wins vs Kills

### ISSUE THREAD

**Issue by Vervatwala** [BattlePlugins/BattleTracker#6]
Hello, there is a bug where BattleTracker counts each kill as a "Win", for example in a free for all where most kills win the winner is not given a +1 in WIns and # of kills in the Kills scoreboard. To illustrate this here is a screenshot of the leaderboards http://i.imgur.com/KByEEOR.png

Sorry if it may not seem clear, I can explain it better if needed. 
Thank u!

**Comment by Europia79** [comment]
Thanks for reporting this issue. I'm surprised nobody has reported this until now.

https://github.com/BattlePluginsDev/BattleArena/blob/master/src/java/mc/alk/arena/listeners/competition/ArenaPlayerKillListener.java#L16

BattleArena isn't calling the correct BattleTracker API method... And from the looks of it, I do not see a BattleTracker API method to add a kill to the database... Unless we're supposed to do some round-about approach, like getting a Stat or PlayerStat object and changing it's internal state ?

**Comment by Europia79** [comment]
This is odd:

https://github.com/BattlePluginsDev/BattleTracker/blob/master/src/java/mc/alk/tracker/objects/Stat.java#L254-L257
https://github.com/BattlePluginsDev/BattleTracker/blob/master/src/java/mc/alk/tracker/serializers/SQLInstance.java#L49-L50
https://github.com/BattlePluginsDev/BattleTracker/blob/master/src/java/mc/alk/tracker/serializers/SQLInstance.java#L115-L116

**Comment by lDucks** [comment]
@Europia79 is this resolved?

**Comment by Europia79** [comment]
@lDucks no, this isn't resolved yet.

But me and Zach do know what the problem is.

**Comment by Zach443** [comment]
@Europia79 I remember testing this with you, I thought we fixed it? Will have to go back through the code and double check.

**Comment by Europia79** [comment]
No, I never did any changes to BattleTracker.

Sorry, I only looked at the code to let you guys know what the problem was.

**Comment by Redned235** [comment]
Wins/Losses will be replaced with Kills/Deaths for default BattleTracker trackers in the [rewrite](https://github.com/BattlePlugins/BattleTracker) version. For plugins like BattleArena where a Win/Loss system may make more sense in certain instances, a custom tracker will be made.

**Comment by Redned235** [comment]
Closing as this is resolved in rewrite.
