### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by tara81** [BattlePlugins/BattleTracker#7]
Also my custom games do not show the stats properly, nether does arenactf (everyone stays at 1250 rating)

http://pastebin.com/3ycaNJhJ

Using spigot 1.8 and battletracker2

**Comment by Europia79** [comment]
Can you copy + paste from your server log file instead of console ? The log file is formatted and easier to read.

**Comment by tara81** [comment]
http://pastebin.com/LRi8d31L server log

**Comment by lDucks** [comment]
@Europia79 is this resolved?

**Comment by Europia79** [comment]
@lDucks sorry, I haven't even looked into this issue at all. It's not resolved yet.

It appears to be a an SQL operation being preformed on a closed ResultSet... originating from the SignController's anonymous Runnable.

**Comment by Redned235** [comment]
Closing due to rewrite.
