### ISSUE TITLE
BattleTracker 2.5.8.10 pushing NoClassFound Errors

### ISSUE THREAD

**Issue by RockStarTragedy** [BattlePlugins/BattleTracker#8]
Platform: Spigot v1_8_R2
Battle Arena Version: v3.9.9.18
World Guard Version: v6.0.0-SNAPSHOT.1605-dfad4b0
World Edit Version: v6.0.2-SNAPSHOT;3370-58aac973
Permission Plugin: PermissionsEx v1.23.2
Other Plugins: I don't believe any other plugins would affect this. If I am mistaken, I will be happy to report back with other plugins I am using.
Description:
Info needed for Replication: I created a Rating sign for the Arena I had created using the format 1st line:[Arena] 2nd line: [Rating]. The ratings automatically generate when the sign is created, and from what I read about regarding the plugin, I am supposed to be able to right click the sign and get my personal stats. However when I try to do this I get this error: java.lang.ClassNotFoundException: mc.alk.util.compat.v1_8_R2.SignHandler. When I looked over the compilation of the plugin, the highest class found under mc\alk\util\compat was v1_7_R1.SignHandler. Is this simply a matter of waiting for an update or is there something else I can do?

**Comment by Europia79** [comment]
http://rainbowcraft.sytes.net/download/plugins/BattleTracker/v2.5.8.11/

Test this out. It should definitely get rid of your errors. Whether or not it actually works is another story... I just finished building it... So I haven't tested it.

**Comment by RockStarTragedy** [comment]
That definitely fixed the errors. The console is happy, and the effect is noticeable when clicking the sign. Thank you for putting that in so fast! :) The only other thing I can suggest, and it's just being picky at this point, was the color of the text when you click on the sign. It turns out gray, which is hard to read.
![battletracker25811](https://cloud.githubusercontent.com/assets/12840981/8145706/722fc984-11e0-11e5-9d3e-b068cea05d9b.png)

**Comment by Europia79** [comment]
No, it's not being picky... That's attention to detail. I appreciate you letting me know. Sorry it took so long to get back to you.

I looked at the code, and it shouldn't be displaying light-gray. No colors are specified, so by default, it should be black. It could be a problem in the Fanciful library that I used... Or something in the Minecraft 1.8 code ?

Anyways, it's should be easier to see now (black):
http://rainbowcraft.sytes.net/download/plugins/BattleTracker/v2.5.8.12/

If I get time, I would like to make it configurable tho.

Also, I was talking to Clovis in IRC about this. I remarked that gold, yellow, and neon green are harder to see on signs in newer versions of Minecraft. He said that if you create a sign with the old versions, then load up a newer version, you'll see the old colors... This suggests that there's another possible solution to this problem: And that's modifying the way the signs are saved to the server & world (probably using NBT - Native Binary Tag).

If you can get someone to make this plugin, that'd be an awesome fix for ALL plugins having this problem.

Anyways, lemme know if you have any more problems.

**Comment by RockStarTragedy** [comment]
This looks beautiful now Europia! Thank you so much :) I have no additional issues with this plugin, and I will be happy to close this thread. Thanks again!
